### ISSUE TITLE
Duplicate key in application properties YAML

### ISSUE THREAD

**Issue by guildenstern70** [quarkiverse/quarkus-logging-json#102]
What if I want to use json=false and additional fields?

In YAML I get duplicate keys error:

```
      json:
        additional-field:
          INDEX:
            value: "u_siem_draft"
          SOURCETYPE:
            value: "seclog:json"
      json: false
```

**Comment by SlyngDK** [comment]
Hi @guildenstern70 
I have not tried to configure with yaml, but maybe setting the full key will help.
```yaml
log.console.json:
  enable: false
  ...
```

**Comment by guildenstern70** [comment]
Ok. I found also another solution:

````
log:
     console:
         json:
             ~: false
             additional-field:
                   INDEX: 
                        value: index
             [...]
```
