### ISSUE TITLE
changing date-format doesn't work

### ISSUE THREAD

**Issue by SMakhrov** [quarkiverse/quarkus-logging-json#155]
I'm trying to change date-format in logs.
I want to use such pattern: 
- format - yyyy-MM-dd'T'HH:mm:ss.SSSZZ
- timezone - UTC
Required example:
2021-12-14T21:58:59.129Z

application.yml:
```
quarkus:
  log:
    console:
      json:
        fields:
          timestamp:
            enabled: true
              date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZZ"
              zone-id: UTC
```

But in logs I still see 2021-12-14T22:08:16.016+0000
What am I doing wrong?
