### ISSUE TITLE
Custom format of file handler not applied when quarkus-logging-json dependency is used

### ISSUE THREAD

**Issue by akridl** [quarkiverse/quarkus-logging-json#346]
In my `pom.xml`, I have a dependency
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-logging-json</artifactId>
        </dependency>
```

My `application.yaml` file:
```yaml
my-config:
  log-file: &log-file
    /tmp/quarkus.log
quarkus:
  log:
    handler:
      file:
        my-file-handler:
          enable: true
          path: *log-file
          format: '%d{yyyy-MM-dd HH:mm:ss} [%p] %s%e%n'
    category:
      "com.example":
        level: DEBUG
        handlers:
          - my-file-handler
```

Example usage of logging (using logger `com.example.GreetingResource`):
```java
@Path("/hello")
@Slf4j
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        log.debug("hello");
        log.info("hi");
        return "Hello from Quarkus REST";
    }
}
```

I request `GET /hello` endpoint and stop the application.
- **Expected behavior**:
  - file `/tmp/quarkus.log` should contain logs of my configured format, e.g.:
```
2025-04-03 15:25:34 [DEBUG] hello
2025-04-03 15:25:34 [INFO] hi
```

- **Actual behavior**:
  - file `/tmp/quarkus.log` contains logs in JSON format, e.g.:
```json
{"timestamp":"2025-04-03T15:25:34.26140817+02:00","sequence":2102,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.example.GreetingResource","level":"DEBUG","message":"hello","threadName":"executor-thread-1","threadId":117,"mdc":{},"ndc":"","hostName":"fedora","processName":"/usr/lib/jvm/java-21-openjdk/bin/java","processId":246572}
{"timestamp":"2025-04-03T15:25:34.263763096+02:00","sequence":2103,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.example.GreetingResource","level":"INFO","message":"hi","threadName":"executor-thread-1","threadId":117,"mdc":{},"ndc":"","hostName":"fedora","processName":"/usr/lib/jvm/java-21-openjdk/bin/java","processId":246572}
```

**Additional information**
- when I comment out the dependency `quarkus-logging-json`, the format of my file handler is correctly applied
- complete example of the reproducer is available at my GitHub: https://github.com/akridl/logging-reproducer
